version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/jest"
    versions:
    - 26.0.22
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.2.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.24.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.30
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
  - dependency-name: next-pwa
    versions:
    - 5.0.6
    - 5.1.4
    - 5.2.1
    - 5.2.3
    - 5.2.5
    - 5.2.9
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.21
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: next
    versions:
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
  - dependency-name: husky
    versions:
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.18
    - 6.1.19
    - 6.1.20
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.16
    - 7.12.17
